services:
  frontend:
    image: prod-anekdootit-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: prod-anekdootit-frontend
  backend:
    image: prod-anekdootit-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: prod-anekdootit-backend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend