# fly.toml app configuration file generated for fs-osa11-anekdootit-pipeline on 2024-09-23T16:07:39+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fs-osa11-anekdootit-pipeline'
primary_region = 'sjc'

[processes]
  app = "npm run start-prod" 
  server = "npx json-server --watch db.json --port 3001"

[[services]]
  processes = ["app"]
  http_checks = []
  internal_port = 3000
  protocol = "tcp"
  script_checks = []

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  strategy = "canary"